db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: "p@ssw0rd"
    POSTGRES_USER: "micropress"
    POSTGRES_DB: "micropress"

backend:
  image: micropress:0.1
  links:
    - db
  environment:
    DATABASE_URL: "jdbc:postgresql://db:5432/micropress"
    USERNAME: "micropress"
    PASSWORD: "p@ssw0rd"
    ACCESS_CONTROL_ALLOW_ORIGIN: "http://localhost:3000"

web-server:
  image: nginx:1.11
  links:
    - backend
  volumes:
    - ./docker/default.dev.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
